-
  branches:
    only:
      - master
  
  version: 0.3.9
  
  skip_tags: true

  image: Visual Studio 2017
      
  init:
  - git config --global core.autocrlf input
  
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: test.csproj
    patch: true

  configuration: Release

  before_build:
    - nuget restore

  nuget:
    account_feed: true

  build:
    parallel: true
    project: test.sln
    
  test:
    assemblies:
      - '**\*.Tests.dll'
  
  on_failure:
    - ps: Update-AppveyorBuild -Version "$($Env:APPVEYOR_BUILD_VERSION).$($Env:APPVEYOR_BUILD_NUMBER)-fail"
  
-
  branches:
    except:
      - master
  
  version: 0.3.9.{build}-{branch}
  
  skip_tags: true

  image: Visual Studio 2017
      
  init:
    - git config --global core.autocrlf input

  
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: test.*
    patch: true

  configuration: Release

  before_build:
    - appveyor-retry nuget restore

  nuget:
    account_feed: true

  build:
    parallel: true
    project: test.sln
    
  test:
    assemblies:
      - '**\*.Tests.dll'
  
  on_failure:
    - ps: Update-AppveyorBuild -Version "$($Env:APPVEYOR_BUILD_VERSION)-fail"
